databases:
  - name: classmaps-db
    plan: free
    databaseName: classmaps
    ipAllowList: []

services:
  - type: web
    name: classmaps
    plan: free
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn classmaps.wsgi"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: classmaps-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.11.7
